name: Hello, World!
on:
  push:
    branches:
      - main
    tags:
      - "!*"
  pull_request:
    branches:
      -main

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - run: node -e 'console.log("Hello, World! on main branch");'
